export const POLICO_CATALOG = [
  { sku: "BLACK-PEPPER-5MM",  name: "Black Pepper 5mm",   category: "spices", defaultUnit: "kg" },
  { sku: "CARDAMOM-LARGE",    name: "Cardamom Large",     category: "spices", defaultUnit: "kg" },
  { sku: "CUMIN-99PURE",      name: "Cumin 99% Pure",     category: "spices", defaultUnit: "kg" },
  { sku: "TURMERIC-5PCT",     name: "Turmeric 5% Curcumin", category: "spices", defaultUnit: "kg" },
  { sku: "CHILI-TEJA-S17",    name: "Chili Teja S17",     category: "spices", defaultUnit: "kg" },
  { sku: "CHICKPEAS-12MM",    name: "Chickpeas 12mm",     category: "pulses", defaultUnit: "MT" },
  { sku: "LENTILS-RED-WHOLE", name: "Red Lentils Whole",  category: "pulses", defaultUnit: "MT" },
  { sku: "MUNG-BEANS-3MM",    name: "Mung Beans 3mm",     category: "pulses", defaultUnit: "MT" },
  { sku: "PALM-OIL-RBD",      name: "RBD Palm Oil",       category: "oils",   defaultUnit: "MT" },
  { sku: "SUNFLOWER-OIL",     name: "Sunflower Oil",      category: "oils",   defaultUnit: "MT" },
  { sku: "COCONUT-OIL-VCO",   name: "Virgin Coconut Oil", category: "oils",   defaultUnit: "MT" },
  { sku: "CASHEW-W320",       name: "Cashews W320",       category: "nuts",   defaultUnit: "kg" },
  { sku: "CASHEW-W240",       name: "Cashews W240",       category: "nuts",   defaultUnit: "kg" },
  { sku: "ALMONDS-NPX",       name: "Almonds NPX",        category: "nuts",   defaultUnit: "kg" },
  { sku: "BASMATI-1121",      name: "Basmati Rice 1121",  category: "grains", defaultUnit: "MT" },
  { sku: "PARBOILED-RICE",    name: "Parboiled Rice 5%",  category: "grains", defaultUnit: "MT" },
  { sku: "GINGER-DRY",        name: "Dry Ginger Whole",   category: "spices", defaultUnit: "kg" },
  { sku: "FENUGREEK",         name: "Fenugreek Seeds",    category: "spices", defaultUnit: "kg" },
  { sku: "CORIANDER-EAGLE",   name: "Coriander Eagle",    category: "spices", defaultUnit: "kg" },
  { sku: "PIGEON-PEAS",       name: "Pigeon Peas Whole",  category: "pulses", defaultUnit: "MT" },
  { sku: "BLACK-GRAM",        name: "Black Gram Whole",   category: "pulses", defaultUnit: "MT" },
  { sku: "SOYBEAN-MEAL",      name: "Soybean Meal 48%",   category: "pulses", defaultUnit: "MT" },
  { sku: "SESAME-NATURAL",    name: "Natural Sesame",     category: "spices", defaultUnit: "kg" },
  { sku: "SESAME-HULLED",     name: "Hulled Sesame",      category: "spices", defaultUnit: "kg" },
  { sku: "PEANUTS-RUNNER",    name: "Runner Peanuts",     category: "nuts",   defaultUnit: "MT" },
  { sku: "RAISINS-GOLDEN",    name: "Golden Raisins",     category: "nuts",   defaultUnit: "kg" },
  { sku: "WHEAT-MILLING",     name: "Milling Wheat",      category: "grains", defaultUnit: "MT" },
  { sku: "MAIZE-YELLOW",      name: "Yellow Maize",       category: "grains", defaultUnit: "MT" },
  { sku: "POPPY-SEEDS",       name: "Poppy Seeds",        category: "spices", defaultUnit: "kg" },
  { sku: "CINNAMON-CASSIA",   name: "Cassia Cinnamon",    category: "spices", defaultUnit: "kg" },
];

export const BASE_PRICES_USD_PER_KG: Record<string, number> = {
  "BLACK-PEPPER-5MM": 5.20, "CARDAMOM-LARGE": 28.50, "CUMIN-99PURE": 3.80, "TURMERIC-5PCT": 1.95, "CHILI-TEJA-S17": 2.40,
  "CHICKPEAS-12MM": 1.10, "LENTILS-RED-WHOLE": 1.05, "MUNG-BEANS-3MM": 1.35, "PALM-OIL-RBD": 0.95, "SUNFLOWER-OIL": 1.20,
  "COCONUT-OIL-VCO": 3.10, "CASHEW-W320": 7.40, "CASHEW-W240": 8.80, "ALMONDS-NPX": 6.20, "BASMATI-1121": 1.30,
  "PARBOILED-RICE": 0.55, "GINGER-DRY": 4.10, "FENUGREEK": 1.50, "CORIANDER-EAGLE": 1.80, "PIGEON-PEAS": 1.20,
  "BLACK-GRAM": 1.65, "SOYBEAN-MEAL": 0.50, "SESAME-NATURAL": 2.30, "SESAME-HULLED": 2.85, "PEANUTS-RUNNER": 1.45,
  "RAISINS-GOLDEN": 3.40, "WHEAT-MILLING": 0.32, "MAIZE-YELLOW": 0.28, "POPPY-SEEDS": 5.80, "CINNAMON-CASSIA": 3.30,
};
